PRAGMA foreign_keys = ON;

INSERT INTO users VALUES (NULL, "Jakub Ucinski", "jakub@email", "cat");
INSERT INTO users VALUES (NULL, "Tony Stark", "tony@email", "dog");
INSERT INTO users VALUES (NULL, "Bruce Banner", "bruce@email", "cat");
INSERT INTO users VALUES (NULL, "Steven G. Rogers", "steven@email", "cat");
INSERT INTO users VALUES (NULL, "Stephen Strange", "strange@email", "cat");
INSERT INTO users VALUES (NULL, "Peter Parker", "peter@email", "cat");
INSERT INTO users VALUES (NULL, "T'Challa", "challa@email", "cat");

INSERT INTO categories VALUES (NULL, 1, "Home");
INSERT INTO categories VALUES (NULL, 1, "Work");
INSERT INTO categories VALUES (NULL, 2, "Home");
INSERT INTO categories VALUES (NULL, 2, "Work"); 
INSERT INTO categories VALUES (NULL, 3, "Home");
INSERT INTO categories VALUES (NULL, 3, "Work"); 
INSERT INTO categories VALUES (NULL, 4, "Home");
INSERT INTO categories VALUES (NULL, 4, "Work"); 
INSERT INTO categories VALUES (NULL, 5, "Home");
INSERT INTO categories VALUES (NULL, 5, "Work"); 
INSERT INTO categories VALUES (NULL, 6, "Home");
INSERT INTO categories VALUES (NULL, 6, "Work");
INSERT INTO categories VALUES (NULL, 7, "Home");
INSERT INTO categories VALUES (NULL, 7, "Work");

INSERT INTO lists VALUES (NULL, 1, "ListA");
INSERT INTO lists VALUES (NULL, 1, "ListB");
INSERT INTO lists VALUES (NULL, 2, "ListA");
INSERT INTO lists VALUES (NULL, 2, "ListB");
INSERT INTO lists VALUES (NULL, 3, "ListA");
INSERT INTO lists VALUES (NULL, 3, "ListB");
INSERT INTO lists VALUES (NULL, 4, "ListA");
INSERT INTO lists VALUES (NULL, 4, "ListB");
INSERT INTO lists VALUES (NULL, 5, "ListA");
INSERT INTO lists VALUES (NULL, 5, "ListB");
INSERT INTO lists VALUES (NULL, 6, "ListA");
INSERT INTO lists VALUES (NULL, 6, "ListB");
INSERT INTO lists VALUES (NULL, 7, "ListA");
INSERT INTO lists VALUES (NULL, 7, "ListB");
INSERT INTO lists VALUES (NULL, 8, "ListA");
INSERT INTO lists VALUES (NULL, 8, "ListB");
INSERT INTO lists VALUES (NULL, 9, "ListA");
INSERT INTO lists VALUES (NULL, 9, "ListB");
INSERT INTO lists VALUES (NULL, 10, "ListA");
INSERT INTO lists VALUES (NULL, 10, "ListB");
INSERT INTO lists VALUES (NULL, 11, "ListA");
INSERT INTO lists VALUES (NULL, 11, "ListB");
INSERT INTO lists VALUES (NULL, 12, "ListA");
INSERT INTO lists VALUES (NULL, 12, "ListB");
INSERT INTO lists VALUES (NULL, 13, "ListA");
INSERT INTO lists VALUES (NULL, 13, "ListB");
INSERT INTO lists VALUES (NULL, 14, "ListA");
INSERT INTO lists VALUES (NULL, 14, "ListB");


INSERT INTO list_items VALUES (NULL, 1, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 1, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 2, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 2, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 3, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 3, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 4, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 4, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 5, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 5, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 6, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 6, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 7, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 7, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 8, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 8, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 9, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 9, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 10, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 10, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 11, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 11, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 12, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 12, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 13, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 13, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 14, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 14, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 15, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 15, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 16, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 16, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 17, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 17, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 18, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 18, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 19, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 19, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 20, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 20, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 21, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 21, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 22, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 22, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 23, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 23, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 24, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 24, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 25, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 25, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 26, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 26, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 27, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 27, "Item2", 0);
INSERT INTO list_items VALUES (NULL, 28, "Item1", 0);
INSERT INTO list_items VALUES (NULL, 28, "Item2", 0);

INSERT INTO shared_lists VALUES (NULL, 1, 1);
INSERT INTO shared_lists VALUES (NULL, 1, 4);
INSERT INTO shared_lists VALUES (NULL, 2, 5);
INSERT INTO shared_lists VALUES (NULL, 3, 10);
INSERT INTO shared_lists VALUES (NULL, 4, 14);

INSERT INTO privilages VALUES (NULL, 3, 1, 3);
INSERT INTO privilages VALUES (NULL, 3, 5, 1);
INSERT INTO privilages VALUES (NULL, 1, 4, 2);
INSERT INTO privilages VALUES (NULL, 2, 7, 2);
INSERT INTO privilages VALUES (NULL, 4, 1, 1);
INSERT INTO privilages VALUES (NULL, 5, 6, 3);